version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment: 
      - POSTGRES_HOST=postgres
    env_file:
      - "./.env"

  postgres:
    image: postgres:13.1-alpine
    env_file:
      - "./.env"
